### ISSUE TITLE
Zipcode 75033 returns no results

### ISSUE THREAD

**Issue by TimothyDJewell** [cfpb/django-hud#10]
Hey guys, great work on this very useful tool.

When I type in 75033 (suburb of Dallas, TX), I see no results.  What's more, the map seems to direct me to Pennsylvania. Nearby zipcodes (75032, 75034) seem to work as expected.  I'm guessing that this is a bug in mapbox, but I couldn't find a way to test it.

**Comment by TimothyDJewell** [comment]
Might be linked to #9

**Comment by rosskarchner** [comment]
Hi @TimothyDJewell -- I've confirmed that Mabox isn't returning results for that zip code. I've opened a ticket with them, and looking into a workaround so that 75033 will work in our tool. Thanks for the report!

**Comment by rosskarchner** [comment]
@TimothyDJewell you should now get appropriate results when you search for 75033.

**Comment by TimothyDJewell** [comment]
I've confirmed.  Thanks!
