### ISSUE TITLE
Zip Code 27592 shows Indonesia and no counselors

### ISSUE THREAD

**Issue by FlyingMissile** [cfpb/django-hud#11]
Zip Code 27592 is around Willow Springs, NC (USA). When entering this zip code on the webpage, the map moves to Indonesia and there are no selected counselors available.

Some kind of geocoding error???

**Comment by rosskarchner** [comment]
Hi @FlyingMissile! This should now be resolved.

**Comment by FlyingMissile** [comment]
Thanks, appears to be working now!
