### ISSUE TITLE
ValueError: Provide API Key

### ISSUE THREAD

**Issue by baltimorekyz06** [cfpb/django-hud#12]
Hi, 

I get the following error when I running python manage.py load_hud_data:
  File "/home/dina/django1.8/local/lib/python2.7/site-packages/geocoder/base.py", line 78, in _get_api_key
    raise ValueError('Provide API Key')
ValueError: Provide API Key

Despite this error, 54 counseling agencys are loaded and I can see them in admin/Hud_Api_Replace/Counseling agencys. 

I added the following variables to myproject/settings.py

GOOGLE_MAPS_API_PRIVATE_KEY = 'XXX_my_private_key'
GOOGLE_MAPS_API_CLIENT_ID  = 'XXX_my_client_id'
DJANGO_HUD_NOTIFY_EMAILS = ['dina@example.com']

Do you have any suggestions about this error?

**Comment by rosskarchner** [comment]
Hello! Our documentation is unfortunately out of date-- we've switched to Mapbox. 

You can configure it using an environment variable (NOT a settings.py variable) , as described here:
http://geocoder.readthedocs.io/providers/Mapbox.html#environment-variables

Speaking just for myself, we should make the geocoder a configurable choice. 

We'll get the README fixed shortly.

**Comment by baltimorekyz06** [comment]
Thank you for your feedback. Adding an environment variable worked like a charm!
